let vetor = [1,3,5,7,9]

console.log(vetor.push(11,13,true,"olá mundo"))
console.log(vetor)
console.log(vetor.length -1)
console.log(vetor)
console.log(vetor.pop())
console.log(vetor)
console.log(vetor.shift())
console.log(vetor)
console.log(vetor.unshift("Bob", "Gil", "Jajá"))
console.log(vetor)
console.log(vetor.slice(2,4))
console.log(vetor)
let vetor2 = vetor.splice(2,4,"Roberto")
console.log(vetor)
console.log(vetor2)
